spring:
  application:
    name: taskmanager

  datasource:
    url: jdbc:postgresql://localhost:5432/taskmanager
    username: taskmanager
    password: taskmanager
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: Asia/Kolkata
        format_sql: false

logging:
  level:
    root: ERROR
    org.springframework: ERROR
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql: ERROR

